# Configs for older then 2.4
bind-key Escape copy-mode
bind-key -t vi-copy Escape cancel
bind-key p paste-buffer
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy V select-line
bind-key -t vi-copy y copy-selection
bind-key -t vi-copy r rectangle-toggle
bind -t vi-copy Y copy-end-of-line
bind -t vi-copy y copy-pipe 'xclip -in -selection clipboard'
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe 'reattach-to-user-namespace pbcopy'
