# Configs for older then 2.1
set -g mode-mouse on
set -g mouse-resize-pane on
set -g mouse-select-pane on
set -g mouse-select-window on
bind - split-window -v
bind | split-window -h
bind c new-window
