# Messaging {
set -g message-command fg=blue,bg=black # Good
# }

# # The modes {
# setw -g clock-mode colour=colour135
# setw -g mode attr=bold,fg=colour196,bg=colour238,
# # }

# The panes {
# set -g pane-border bg=colour235,fg=colour238
set -g pane-active-border bg=colour236,fg=colour51 #Good
# }

# # The statusbar {
# set -g status attr=dim
#
# setw -g window-status-current fg=colour81,bg=colour238,attr=bold
#
# setw -g window-status fg=colour138,bg=colour235,attr=none
#
# setw -g window-status-bell attr=bold,fg=colour255,bg=colour1
# # }

# # The messages {
# set -g message attr=bold,fg=colour232,bg=colour166
# # }
